### ISSUE TITLE
`as_flextable` generic and methods for design summary objects

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#108]
It would be great to create new S3 methods for generating tables for the design summary objects, using flextable as the backend.

One could do by following the spirit in the existing [`as_gt()` methods](https://github.com/Merck/gsDesign2/blob/main/R/as_gt.R).

An advantage of flextable outputs is that they can be easily [exported](https://ardata-fr.github.io/flextable-book/rendering.html) to docx files, convenient for the downstream workflow.

**Comment by LittleBeannie** [comment]
@nanxstats will lead SP members for this ticket. Please feel free to reach out to me if there are any technical questions.

**Comment by fb-elong** [comment]
Please put me as the single assignee for this task.

**Comment by fb-elong** [comment]
If the purpose is only to create RTF output. We should probably only have one version. either using `r2rtf` or `flextable` but not both in the package. 

Suggest to close this one.

**Comment by nanxstats** [comment]
> If the purpose is only to create RTF output. We should probably only have one version. either using `r2rtf` or `flextable` but not both in the package.
> 
> Suggest to close this one.

For flextable, the goal is to create `docx` output, suggested by @yuliasidi.

**Comment by elong0527** [comment]
For end user, `rtf` and `docx`  are the same thing that will only be opened from Microsoft Office. 

Maybe I did not get the point why we need to create both. To simplify maintenance and reduce package dependency, I suggest we only pick one in gsDesign2

 For end user, they can generate format as needed because we can output the data frame before we do formatting. I think that will follow the open-close principal.

**Comment by nanxstats** [comment]
Understood. I guess there was a reason why docx and flextable were asked in particular. That being said, let's prioritize RTF and close this for now. In case `.docx` or flextable outputs are specifically needed in the future, we can revisit.
