### ISSUE TITLE
Accelerate code examples with elapsed time > 5s

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#124]
I see this note when running `R CMD check`:

```text
* checking examples ... [36s/36s] NOTE
Examples with CPU (user + system) or elapsed time > 5s
                   user system elapsed
summary.gs_design 7.590  0.060   7.653
gs_design_combo   6.282  0.069   6.366
```

This likely will be problematic on CRAN check machines, too, as their [server](https://cran.r-project.org/web/checks/check_flavors.html)'s single-core performance is probably not as high as my devices. We should seek ways to reduce the running time of these code examples.

**Comment by LittleBeannie** [comment]
Yes, it is a problem for max combo, since its computation is complicated. A simple solution is to use `\dontrun{}` environment. But I guess @elong0527 may have a better solution.

**Comment by elong0527** [comment]
Let’s do that :)

**Comment by howardbaek** [comment]
Seems like the goal is to submit to CRAN, so I'm leaving a few notes on CRAN while reading [R packages](https://r-pkgs.org/man.html#sec-man-examples).

- [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html)
- Submitting to CRAN: ALL examples must run in under 10 minutes.

**Comment by howardbaek** [comment]
Summary table of time elapsed for examples in `gs_XXX.R`:

| R Script | Example | Elapsed Time
| ------------- | ------------- |------------- | 
| `gs_design_combo.R`  | example 1, example 2 | 10.8 sec |
| `gs_design_ahr.R`  | example 4, example 5 | 10.5 sec |
| `gs_info_ahr.R` |  example 1, example 3 | 10.1 sec |
| `gs_power_ahr.R` | example 1, example 3, example 4 | 14.1 sec  |
| `gs_power_combo.R` | example 1 | 8.5 seconds |
| `gs_power_wlr.R` | example 1, example 4 | 14.3 seconds |

**Comment by LittleBeannie** [comment]
> Summary table of time elapsed for examples in `gs_XXX.R`:
> 
> R Script	Example	Elapsed Time
> `gs_design_combo.R`	example 1, example 2	10.8 sec
> `gs_design_ahr.R`	example 4, example 5	10.5 sec
> `gs_info_ahr.R`	example 1, example 3	10.1 sec
> `gs_power_ahr.R`	example 1, example 3, example 4	14.1 sec
> `gs_power_combo.R`	example 1	8.5 seconds
> `gs_power_wlr.R`	example 1, example 4	14.3 seconds

Excellent work! A tiny clarification question: is the "elapsed time" the total elapsed time for multiple examples? I guess we need the running time for individual examples. If it is more than 5 sec, then put it in the `dontrun` environment.

**Comment by howardbaek** [comment]
I've updated the table with the running time for individual examples. In `gs_info_ahr.R`, example 3 contained two function runs. The first run is labelled example 3.1, the second example 3.2.

I've also put in `dontrun{}` environment to those examples in the table since their elapsed times were more than 5 sec.

**Comment by LittleBeannie** [comment]
> I've updated the table with the running time for individual examples. In `gs_info_ahr.R`, example 3 contained two function runs. The first run is labelled example 3.1, the second example 3.2.
> 
> I've also put in `dontrun{}` environment to those examples in the table since their elapsed times were more than 5 sec.

Awesome! Could you please make a PR and assigned me (and Nan) as reviewers?

**Comment by nanxstats** [comment]
This is the feedback you would normally get for using `\dontrun{}`:

> \dontrun{} should only be used if the example really cannot be executed (e.g. because of missing additional software, missing API keys, ...) by the user. That's why wrapping examples in \dontrun{} adds the comment ('# Not run:') as a warning for the user. Is this necessary?
>
> If not, please unwrap the examples if they are executable in < 5 sec, or replace \dontrun{} with \donttest{}.

So, for the cases where the example code can run but taking > 5 seconds, we should wrap them in `\donttest{}`.

**Comment by LittleBeannie** [comment]
> This is the feedback you would normally get for using `\dontrun{}`:
> 
> > \dontrun{} should only be used if the example really cannot be executed (e.g. because of missing additional software, missing API keys, ...) by the user. That's why wrapping examples in \dontrun{} adds the comment ('# Not run:') as a warning for the user. Is this necessary?
> > If not, please unwrap the examples if they are executable in < 5 sec, or replace \dontrun{} with \donttest{}.
> 
> So, for the cases where the example code can run but taking > 5 seconds, we should wrap them in `\donttest{}`.

Thanks for the excellent suggestion! `\donttest{}` is better.

**Comment by howardbaek** [comment]
I did notice the R packages book has this [footnote](https://r-pkgs.org/man.html#fn12):

> You used to be able to use \donttest{} for a similar purpose, but we no longer recommend it because CRAN sets a special flag that causes the code to be executed anyway.[↩︎](https://r-pkgs.org/man.html?q=\dont#fnref12) 

But, an [initial search](https://github.com/search?q=org%3Acran+%5Cdonttest&type=code) of the Unofficial read-only mirror of all CRAN R packages on GitHub shows 15.3K functions that use \donttest{}: 

Other discussion of \donttest{} vs \dontrun{}
- https://github.com/dankelley/oce/issues/1798
- https://github.com/r-lib/devtools/issues/2216

**Comment by nanxstats** [comment]
@howardbaek Sure we can discuss this. I think it's clear that `\donttest` is the right option here for the purpose of eliminating the > 5 seconds note - although CRAN actually running such examples seems a confusing fact judged by the tag name.

**Comment by howardbaek** [comment]
> @howardbaek Sure we can discuss this. I think it's clear that `\donttest` is the right option here for the purpose of eliminating the > 5 seconds note - although CRAN actually running such examples seems a confusing fact judged by the tag name.

Okay, I changed all the `\dontrun` code to `\donttest` and just submitted a PR.
