### ISSUE TITLE
`as_r2rtf_*` generics and methods for design summary objects

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#130]
I'm creating this issue as a placeholder in case we decide to move forward on this next year.

It would be great to create new S3 methods for generating tables for the design summary objects, using r2rtf as the backend and promoting the r4csr style, following the general table format in the existing [as_gt() methods](https://github.com/Merck/gsDesign2/blob/main/R/as_gt.R).

Inspired by the [huxtable example in gtsummary](https://www.danieldsjoberg.com/gtsummary/reference/as_hux_table.html), I think we can define two methods to make things flexible for users:

- `as_r2rtf_table()`: returns the object before `rtf_encode()`
- `as_r2rtf_rtf()`: has a `file` argument, (invisibly) returns output path.. or the input `file` argument (according to the tidyverse style guide), and does `as_r2rtf_table() |> rtf_encode() |> write_rtf()`.

**Comment by elong0527** [comment]
@LittleBeannie , @nanxstats; could we re-assign the task to @howardbaek ?

**Comment by LittleBeannie** [comment]
> @LittleBeannie , @nanxstats; could we re-assign the task to @howardbaek ?

Sure! Howard is not in the team yet. I just sent him an invitation and will assign the ticket to him later.

**Comment by LittleBeannie** [comment]
> 

Just for curiosity: shall we call it `as_rtf_table` and `as_rtf` instead?

**Comment by nanxstats** [comment]
> Just for curiosity: shall we call it `as_rtf_table` and `as_rtf` instead?

I feel `as_r2rtf_table()` and `as_r2rtf_rtf()` would allow maximum extensibility because you can add other table backends that also generate RTF in the future, for example, `as_gt_rtf()`.

In summary, the first components is always the table backend name, with an optional second component being the output type. This is consistent with the naming scheme in gtsummary.

**Comment by LittleBeannie** [comment]
> > Just for curiosity: shall we call it `as_rtf_table` and `as_rtf` instead?
> 
> I feel `as_r2rtf_table()` and `as_r2rtf_rtf()` would allow maximum extensibility because you can add other table backends that also generate RTF in the future, for example, `as_gt_rtf()`.
> 
> In summary, the first components is always the table backend name, with an optional second component being the output type. This is consistent with the naming scheme in gtsummary.

Thanks for the explanation!

**Comment by nanxstats** [comment]
Looks like this has been implemented in https://github.com/Merck/gsDesign2/pull/285 so I'm closing this.
