### ISSUE TITLE
Proofread and re-organize existing vignettes

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#131]
Hi @keaven, please work on branch #131 to tidy up the existing vignettes. It also works if you help to leave some notes here and I will follow up.

**Comment by howardbaek** [comment]
Hi @LittleBeannie, I can start working on this issue too as I read the vignettes to familiarize myself with this package

**Comment by LittleBeannie** [comment]
> Hi @LittleBeannie, I can start working on this issue too as I read the vignettes to familiarize myself with this package.

Thanks! Just add you as another assignee.

**Comment by nanxstats** [comment]
@LittleBeannie Can this issue be closed? Or do we still expect a further review of the current vignettes (considering most of them except the start guide have been moved into `vignettes/articles/`)?
