### ISSUE TITLE
Fix the remaining 500 code linting issues on style

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#151]
I know it's a big ask... but we should push for a complete fix for the code linting issues (~560 remaining). Then the lintr workflow will pass. Most of the remaining issues are about the snake_case and lines exceeding 120 characters.

To see the linting issues locally, run:

```r
x <- lintr::lint_package()
x
```

Double clicking each marker in the results will jump to the corresponding file and line.

**Comment by LittleBeannie** [comment]
> I know it's a big ask... but we should push for a complete fix for the code linting issues (~560 remaining). Then the lintr workflow will pass. Most of the remaining issues are about the snake_case and lines exceeding 120 characters.
> 
> To see the linting issues locally, run:
> 
> ```r
> x <- lintr::lint_package()
> x
> ```
> 
> Double clicking each marker in the results will jump to the corresponding file and lint

Thanks for listing the shortcut to fix the lintr issue. It becomes easier when I know where the problem is!
