### ISSUE TITLE
Standardize enumerated options naming

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#22]
I don't think the naming convention of the enumerated options in function arguments is covered by the current [syntax style guide](https://style.tidyverse.org/syntax.html) for tidyverse, but in a consistent manner with variables/functions, I would propose to use lower case abbreviations and snake case for the enumerated options in function arguments. This means

```r
# Bad
f <- function (method = c("AHR", "WLR", ...) { }

# Good
f <- function (method = c("ahr", "wlr"), ...) { }
```

```r
# Bad
f <- function (approx= c("event driven", "asymptotic", "generalized schoenfeld", ...) { }

# Good
f <- function (approx= c("event_driven", "asymptotic", "generalized_schoenfeld", ...) { }
```

This style is also consistent with tensorflow and keras, and would make your code look consistent in style.

If not done already, we should also make an effort to [enumerate all possible options](https://design.tidyverse.org/def-enum.html) in the function definition, and document them properly.

cc @keaven @elong0527

**Comment by elong0527** [comment]
Agree. Would be good to have an PR to review the impact before we start to implement testing.

**Comment by keaven** [comment]
Thanks for getting us on a good page...I guess we should have our coding conventions on a portal page somewhere or in a vignette in gsDesign2.

**Comment by nanxstats** [comment]
Great, I will send a PR to create a style guide & rules vignette.

There is a good [chapter](https://abseil.io/resources/swe-book/html/ch08.html) about this topic in the SWE book.
