### ISSUE TITLE
Format footnote numbers using decimal notation

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#222]
At the bottom of the readme, the `as_gt()` output footnote 3 says:

> 3... The smaller value subtracts the probability of crossing a futility bound before crossing an efficacy bound at a later analysis (0.025 - **6e-04** = 0.0244) under the null hypothesis.

We should format 0.025 - **6e-04** = 0.0244 as 0.025 - **0.0006** = 0.0244 and enforce decimal notation for all numbers in the footnotes.

This is because scientific notation might create potential confusion and misinterpretation sometimes. Using decimal notation will ensure clarity and consistency, making it easier for a wider audience including regulators and non-technical stakeholders to understand the information being presented.

**Comment by LittleBeannie** [comment]
Hi @nanxstats , I will not have the bandwidth for this issue in the next 2 months. If possible, could you please find other people from BAAMR for this?

**Comment by LittleBeannie** [comment]
@nanxstats will lead SP members for this ticket. Please feel free to reach out to me if there are any technical questions.
