### ISSUE TITLE
Improve `as_gt()` S3 methods documentation

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#23]
The current documentation for `as_gt()`, `as_gt(<fixed_design>)`, `as_gt(<gs_design>)` can be improved from a few aspects:

1. We should document `...` better, specifically, in that `...` documentation, use a link to the function on what `...` is passed to so that users know what additional options are possible by following that link. 👉 How to create [function links](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-formatting.html#function-links) in roxygen2.

2. One thing I found helpful is when people click the `as_gt()` link in vignettes, they should be able to see what specific arguments are available - currently it's not because there is not too much on the `as_gt()` page.

   A simple solution is to add the internal function links to `as_gt(<fixed_design>)` and `as_gt(<gs_design>)` on the `as_gt()` page.

   Alternatively, you can consider merging the documentation page for similar functions into one topic (i.e., one page on pkgdown site). This can be done via [`@rdname`](https://r-pkgs.org/man.html#sec-multiple-functions). `@inheritParams` is also frequently used together for such things. [Example](https://vctrs.r-lib.org/reference/list_of.html) in vctrs. This merging can be very useful in reducing duplicated information, but can also be confusing if not used properly.

cc @keaven @elong0527

**Comment by yuliasidi** [comment]
Is it possible to have a similar output to the one produced by `gsDesing::gsBoundSummary()`?

One thing for consideration: `gt` produces a picture, it might be useful to have an output function that produces an editable table (for instance `flextable` )

**Comment by nanxstats** [comment]
I'm not sure if "similar output" means content formatting or the table output type (kable, flextable, etc.).

**For output type**, yes, we intentionally named the current method `as_gt()` because the goal is to have multiple table backends (output types) supported, for example:

```
as_flex_table()
as_kable()
as_kable_extra()
...
```

You can see a similar concept built in [gtsummary](https://www.danieldsjoberg.com/gtsummary/reference/#output-types) for regression models.

We will surely welcome a volunteer to help expand the output types here!

**For content formatting**, I guess the format used here was thoughtfully (re)designed to accommodate broader needs. However, if it makes sense, it might be technically possible to add an `as_gsd()` output type to remaster the classic format.

**Comment by howardbaek** [comment]
@nanxstats  I've finished point 2 by merging the documentation for `as_gt()`, `as_gt(<fixed_design>)`, `as_gt(<gs_design>)` into one page. Can I get some clarification on point 1?

**Comment by nanxstats** [comment]
@howardbaek Similar to this: https://github.com/Merck/pkglite/blob/master/R/unpack.R#L32

**Comment by howardbaek** [comment]
> @howardbaek Similar to this: https://github.com/Merck/pkglite/blob/master/R/unpack.R#L32

So..something like `Additional parameters for [gt::gt()]` ?

**Comment by nanxstats** [comment]
@howardbaek I think so - the point is that this would create a link to `gt::gt()` in the help page so that people can follow that link to see what exact parameters are supported by the function. Just make sure you are referring to the correct function that the `...` is passed into.

**Comment by howardbaek** [comment]
@LittleBeannie The `...` isn't used anywhere in `as_gt()`: https://github.com/Merck/gsDesign2/blob/main/R/as_gt.R#L22

Can I just get rid of this parameter in the generic and methods?

**Comment by LittleBeannie** [comment]
> @LittleBeannie The `...` isn't used anywhere in `as_gt()`: https://github.com/Merck/gsDesign2/blob/main/R/as_gt.R#L22 Can I just get rid of this parameter in the S3 generic and methods?
> 
> cc @nanxstats

Personally, I recommend keeping it there. If you delete it, there will be an error if you give it a try

**Comment by howardbaek** [comment]
I removed `...` from the methods (`as_gt.fixed_design()` and `as_gt.gs_design()`) and used `devtools::load_all()` to run the examples and everything ran without error. This is the updated `as_gt.R` file that I am experimenting with: https://github.com/Merck/gsDesign2/blob/23-improve-as_gt-s3-methods-documentation/R/as_gt.R
