### ISSUE TITLE
Release of gsDesign2 v1.0.9

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#233]
Prepare for release

- [x] Check current CRAN check results
- [x] Check licensing of included files
- [x] Review pkgdown reference index for, e.g., missing topics
- [x] Bump version
- [x] Update `cran-comments.md` (optional)
- [x] Update NEWS.md
- [x] Review pkgdown website
- [x] `urlchecker::url_check()`
- [x] Check with local machine
- [x] Check with GitHub Actions
- [x] Check with win-builder

Submit to CRAN

- [ ] Draft GitHub release
- [ ] Submit to CRAN via web form
- [ ] Approve emails

Wait for CRAN

- [ ] Accepted :tada:
- [ ] Post on r-packages mailing list
- [ ] Tweet

**Comment by nanxstats** [comment]
On CRAN 2023-06-20.
