### ISSUE TITLE
Why functions in `helper_function.R` are exported?

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#253]
Could we review if it is necessary to export helper functions？ 

https://merck.github.io/gsDesign2/reference/index.html#low-level-helpers

**Comment by nanxstats** [comment]
Sure, it might be productive to prioritize functions that are not currently used anywhere in code examples and vignettes, as it would require non-trivial changes to the code examples and vignette to un-export previously exported functions.

Or do you mean we need one (or multiple) more accurate file name(s) + section name(s) to organize these functions instead of simply using the generic term "helper"?

**Comment by elong0527** [comment]
Feel those functions should not exported to user. 

For example, why would a user need `h1` function.

**Comment by nanxstats** [comment]
Sure, that makes sense. My point was, `h1()` is used in `gs_spending_bound()` examples in both function documentation and vignettes:

https://merck.github.io/gsDesign2/articles/usage-gs-spending-bound.html
https://merck.github.io/gsDesign2/reference/gs_spending_bound.html

So they need to be rewritten or removed to un-export `h1()`

**Comment by elong0527** [comment]
Got it. If that's the only reason to keep them exported. Let me find way to rewrite them. 

btw, would you feel vignettes is OK to refer internal function if we did not submit the vignettes to CRAN? (Given some vignettes is to discuss internal logic derivation for technical details)

**Comment by nanxstats** [comment]
> Got it. If that's the only reason to keep them exported. Let me find way to rewrite them.
> 
> btw, would you feel vignettes is OK to refer internal function if we did not submit the vignettes to CRAN? (Given some vignettes is to discuss internal logic derivation for technical details)

Sounds great.

And good point - it might be ok to use `:::` in the (article) vignettes because `vignettes/articles/` are not even built into the tarball when running `R CMD build`. So the strict rules from `R CMD check` will likely not apply to those Rmd files.

**Comment by LittleBeannie** [comment]
Decision: we will keep the following functions exported:
[fixed_design()](https://merck.github.io/gsDesign2/reference/fixed_design.html)
Fixed design sample size
Average hazard ratio
Functions for the average hazard ratio (AHR) method.

[ahr()](https://merck.github.io/gsDesign2/reference/ahr.html)
Average hazard ratio under non-proportional hazards (test version)
[expected_time()](https://merck.github.io/gsDesign2/reference/expected_time.html)
Predict time at which a targeted event count is achieved
[expected_event()](https://merck.github.io/gsDesign2/reference/expected_event.html)
Expected events observed under piecewise exponential model
[gs_info_ahr()](https://merck.github.io/gsDesign2/reference/gs_info_ahr.html)
Information and effect size based on AHR approximation
[gs_power_ahr()](https://merck.github.io/gsDesign2/reference/gs_power_ahr.html)
Group sequential design power using average hazard ratio under non-proportional hazards
[gs_design_ahr()](https://merck.github.io/gsDesign2/reference/gs_design_ahr.html)
Group sequential design using average hazard ratio under non-proportional hazards
Weighted logrank
Functions for the weighted logrank test (WLR) method.

[wlr_weight_fh()](https://merck.github.io/gsDesign2/reference/wlr_weight.html) [wlr_weight_1()](https://merck.github.io/gsDesign2/reference/wlr_weight.html) [wlr_weight_n()](https://merck.github.io/gsDesign2/reference/wlr_weight.html) [wlr_weight_mb()](https://merck.github.io/gsDesign2/reference/wlr_weight.html)
Weight functions for weighted log-rank test
[gs_info_wlr()](https://merck.github.io/gsDesign2/reference/gs_info_wlr.html)
Information and effect size for weighted log-rank test
[gs_power_wlr()](https://merck.github.io/gsDesign2/reference/gs_power_wlr.html)
Group sequential design power using weighted log rank test under non-proportional hazards
[gs_design_wlr()](https://merck.github.io/gsDesign2/reference/gs_design_wlr.html)
Group sequential design using weighted log-rank test under non-proportional hazards
MaxCombo
Functions for the MaxCombo method.

[gs_info_combo()](https://merck.github.io/gsDesign2/reference/gs_info_combo.html)
Information and effect size for MaxCombo test
[gs_spending_combo()](https://merck.github.io/gsDesign2/reference/gs_spending_combo.html)
Derive spending bound for MaxCombo group sequential boundary
[gs_power_combo()](https://merck.github.io/gsDesign2/reference/gs_power_combo.html)
Group sequential design power using MaxCombo test under non-proportional hazards
[gs_design_combo()](https://merck.github.io/gsDesign2/reference/gs_design_combo.html)
Group sequential design using MaxCombo test under non-proportional hazards
Risk difference
Functions for risk differences.

[gs_info_rd()](https://merck.github.io/gsDesign2/reference/gs_info_rd.html)
Information and effect size under risk difference
[gs_power_rd()](https://merck.github.io/gsDesign2/reference/gs_power_rd.html)
Group sequential design power of binary outcome measuring in risk difference
[gs_design_rd()](https://merck.github.io/gsDesign2/reference/gs_design_rd.html)
Group sequential design of binary outcome measuring in risk difference
Input definition
Helper functions to define inputs for study design.

[define_enroll_rate()](https://merck.github.io/gsDesign2/reference/define_enroll_rate.html)
Define enrollment rate
[define_fail_rate()](https://merck.github.io/gsDesign2/reference/define_fail_rate.html)
Define fail rate
Summary and display tables
Functions to summarize fixed / group sequential design results.

[summary(<fixed_design>)](https://merck.github.io/gsDesign2/reference/summary.html) [summary(<gs_design>)](https://merck.github.io/gsDesign2/reference/summary.html)
Summary for fixed design or group sequential design objects
[as_gt()](https://merck.github.io/gsDesign2/reference/as_gt.html)
Convert summary table of a fixed or group sequential design object to a gt object
[to_integer()](https://merck.github.io/gsDesign2/reference/to_integer.html)
Rounds sample size to an even number for equal design
Boundary functions
Functions to specify the upper and lower bound in group sequential designs. They are not recommended to use alone. Instead, they should be used companied with gs_design_npe, gs_power_npe, ect..

[gs_b()](https://merck.github.io/gsDesign2/reference/gs_b.html)
Default boundary generation
[gs_spending_bound()](https://merck.github.io/gsDesign2/reference/gs_spending_bound.html)
Derive spending bound for group sequential boundary
Low-level helpers
Functions to calculate sample size or number of events under non-constant treatment effect over time.

[gs_power_npe()](https://merck.github.io/gsDesign2/reference/gs_power_npe.html)
Group sequential bound computation with non-constant effect
[gs_design_npe()](https://merck.github.io/gsDesign2/reference/gs_design_npe.html)
Group sequential design computation with non-constant effect and information
[expected_accrual()](https://merck.github.io/gsDesign2/reference/expected_accrual.html)
Piecewise constant expected accrual
[ppwe()](https://merck.github.io/gsDesign2/reference/ppwe.html)
Piecewise exponential cumulative distribution function
[s2pwe()](https://merck.github.io/gsDesign2/reference/s2pwe.html)
Approximate survival distribution with piecewise exponential distribution

**Comment by LittleBeannie** [comment]
Let's work on this issue when #261 is merged.

**Comment by fb-elong** [comment]
Please review the diff, examples has been udpated.
