### ISSUE TITLE
Remove `npsurvSS` dependency

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#257]
`npsurvSS` is used for WLR design, will try to remove the dependency to improve consistency of the gsDesign2 package between `ahr` and `wlr` method.

**Comment by LittleBeannie** [comment]
It looks like the WLR test in gsDesign2 depends on a lot with npsurvSS. Since we previous built connection with the npsurvSS maintainer, and it looks like npsurvSS is still in good maintainance.  

I will close this issue for now. We can definitely re-open it on needed base.
