### ISSUE TITLE
`ahr` split function with simple = TRUE / FALSE

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#262]
The output of a function should be the same structure. 

The output wen `simple = FALSE` is not even generate AHR. Propose to split them into two functions: 

`ahr` -> original one with simple = TRUE 
`ahr_hr` -> report hr of each period. 

```
>  ahr(enroll_rate = enroll_rate, fail_rate = fail_rate, total_duration = c(15, 30))
# A tibble: 2 × 5
   time   ahr event  info info0
  <dbl> <dbl> <dbl> <dbl> <dbl>
1    15 0.812  91.0  22.3  22.7
2    30 0.712 222.   54.4  55.4
> ahr(enroll_rate = enroll_rate, fail_rate = fail_rate, total_duration = c(15, 30), simple = FALSE)
# A tibble: 4 × 7
   time stratum     t    hr event  info info0
  <dbl> <chr>   <dbl> <dbl> <dbl> <dbl> <dbl>
1    15 All         0   1    53.9 13.5  13.5 
2    15 All         4   0.6  37.1  8.86  9.28
3    30 All         0   1    74.1 18.5  18.5 
4    30 All         4   0.6 147.  35.9  36.9 
```

**Comment by nanxstats** [comment]
I completely agree. More generally, "type-stable" functions are preferred: https://design.tidyverse.org/out-type-stability.html

**Comment by LittleBeannie** [comment]
`ahr` -> original ahr function with simple = TRUE
`pw_hr_info` -> original ahr function with simple = FALSE 
`ahr` will call ``pw_hr_info`

**Comment by elong0527** [comment]
Great! Maybe we can brainstorm a better function name. 

If the function will become a general utility function, maybe `piecewise_hazard_ratio`   

If the function only apply to AHR method, maybe starting from `ahr_xxx` e.g. `ahr_piecewise`.

@nanxstats, you must have better suggestion on name convention.

**Comment by LittleBeannie** [comment]
> Great! Maybe we can brainstorm a better function name.
> 
> If the function will become a general utility function, maybe `piecewise_hazard_ratio`
> 
> If the function only apply to AHR method, maybe starting from `ahr_xxx` e.g. `ahr_piecewise`.
> 
> @nanxstats, you must have better suggestion on name convention.

Can we call it `pw_info`? Because it basically computes the statistical information for the piecewise model. Considering `pw_info` is also used in `gs_info_wlr`, let's not start it with `ahr_xxx`.
