### ISSUE TITLE
Remove old files in `inst/` folder

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#266]
Could we remove old functions under `inst/` folder?

**Comment by LittleBeannie** [comment]
> Could we remove old functions under `inst/` folder?

I personally prefer to keep these old functions. We might have some new features in the future, and the old functions can always be a testing guard.

**Comment by nanxstats** [comment]
Perhaps we need a gsDesign2-legacy repo so it's in a proper package form? Just like Hadley's ggplot1 repo: https://github.com/hadley/ggplot1.

**Comment by LittleBeannie** [comment]
> Perhaps we need a gsDesign2-legacy repo so it's in a proper package form? Just like Hadley's ggplot1 repo: https://github.com/hadley/ggplot1.

So does gsDesign2 depend on gsDesign2-legacy?

**Comment by nanxstats** [comment]
> > Perhaps we need a gsDesign2-legacy repo so it's in a proper package form? Just like Hadley's ggplot1 repo: https://github.com/hadley/ggplot1.
> 
> So does gsDesign2 depend on gsDesign2-legacy?

No, they are entirely isolated. gsDesign2-legacy is for archiving and historical reference only, like the ggplot1 repo.

**Comment by LittleBeannie** [comment]
> > > Perhaps we need a gsDesign2-legacy repo so it's in a proper package form? Just like Hadley's ggplot1 repo: https://github.com/hadley/ggplot1.
> > 
> > 
> > So does gsDesign2 depend on gsDesign2-legacy?
> 
> No, they are entirely isolated. gsDesign2-legacy is for archiving and historical reference only, like the ggplot1 repo.

Can I ask 1 more naive question? So if I test gsDesign2 by some functions in gsDesign2-legacy, how can I import gsDesign2-legacy?

**Comment by nanxstats** [comment]
> Can I ask 1 more naive question? So if I test gsDesign2 by some functions in gsDesign2-legacy, how can I import gsDesign2-legacy?

By installing it from that repo I guess. A different package name can be used in `DESCRIPTION` to avoid namespace conflicts.

**Comment by LittleBeannie** [comment]
> > Can I ask 1 more naive question? So if I test gsDesign2 by some functions in gsDesign2-legacy, how can I import gsDesign2-legacy?
> 
> By installing it from that repo I guess. A different package name can be used in `DESCRIPTION` to avoid namespace conflicts.

Does it mean gsDesign2 have a dependency on gsDesign2-legacy?

**Comment by nanxstats** [comment]
> Does it mean gsDesign2 have a dependency on gsDesign2-legacy?

No.

**Comment by nanxstats** [comment]
Decision: move the important code from `inst/` to `tests/` for formal accordance testing.
