### ISSUE TITLE
Location of old functions

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#269]
Not sure it is proper to access those functions under `inst/old_function`. 

If those functions are only used for testing, I feel they should be saved under the `tests/` folder. 

https://github.com/Merck/gsDesign2/blob/main/tests/testthat/test-oldversion-ahr.R#L1-L3

Any suggestion? @nanxstats

**Comment by nanxstats** [comment]
Sure... I don't think I have a better proposal.

**Comment by LittleBeannie** [comment]
save the testing code in `test-oldversion-xx` into `test-developer-xx`
