### ISSUE TITLE
Comparison between gsDesign, gsDesign2, and EAST

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#27]
@LittleBeannie Please add some context and details here.

**Comment by nanxstats** [comment]
Update: It seems that we want to do some updates to gsDesign2 first to offer the essential options. After that, let's make an effort to merge the vignette in the `27-comparision-between-gsdesign-gsdesign2-and-east` branch.

**Comment by nanxstats** [comment]
So... is there a decision made? I'm not seeing that branch anymore and it's surely not merged.

**Comment by LittleBeannie** [comment]
> So... is there a decision made? I'm not seeing that branch anymore and it's surely not merged.

yes, we will switch the post internally.

**Comment by nanxstats** [comment]
> > So... is there a decision made? I'm not seeing that branch anymore and it's surely not merged.
> 
> yes, we will switch the post internally.

OK that's good to know!
