### ISSUE TITLE
Release gsDesign2 v1.1.0 to CRAN

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#283]
Prepare for release

- [x] Check current CRAN check results
- [x] Check licensing of included files
- [x] Review pkgdown reference index for, e.g., missing topics
- [x] Bump version
- [x] Update `cran-comments.md` (optional)
- [x] Update NEWS.md
- [x] Review pkgdown website
- [x] `urlchecker::url_check()`
- [x] Check with local machine
- [x] Check with GitHub Actions
- [x] Check with win-builder

Submit to CRAN

- [x] Draft GitHub release
- [x] Submit to CRAN via web form
- [x] Approve emails

Wait for CRAN

- [x] Accepted :tada:
- [ ] Post on r-packages mailing list
- [ ] Tweet

**Comment by LittleBeannie** [comment]
Hi @nanxstats, I met an error when building .tar.gz file for gsDesign2. Do you have any idea to fix it?

![image](https://github.com/Merck/gsDesign2/assets/43153957/bed0ebaf-13f8-479d-8c20-72997e1676d7)

**Comment by nanxstats** [comment]
> Hi @nanxstats, I met an error when building .tar.gz file for gsDesign2. Do you have any idea to fix it?

Install htmltools first?

**Comment by LittleBeannie** [comment]
> > Hi @nanxstats, I met an error when building .tar.gz file for gsDesign2. Do you have any idea to fix it?
> 
> Install htmltools first?

It looks the install and library of htmltools don't work....
