### ISSUE TITLE
`info` and `info0` as `info_scale` is modified

### ISSUE THREAD

**Issue by mjg211** [Merck/gsDesign2#287]
If I run

```r
> gs_design_ahr()$analysis
# A tibble: 1 × 9
  analysis  time     n event   ahr theta  info info0 info_frac
     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>     <dbl>
1        1    36  476.  292. 0.683 0.381  71.7  73.0         1
```
I can see that `info0` has the expected `events`/4 relationship. If instead I run

```r
> gs_design_ahr(info_scale="h0_info")$analysis
# A tibble: 1 × 9
  analysis  time     n event   ahr theta  info info0 info_frac
     <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>     <dbl>
1        1    36  481.  295. 0.683 0.381  72.5  72.5         1
```

this relationship now doesn't hold either for `info` or `info0`. This doesn't seem logical to me.

Looking in the code for `gs_design_ahr`, it feels like the offending line might be:

```r
inflac_fct <- (allout %>% filter(analysis == n_analysis, 
        bound == "upper"))$info/(y %>% filter(analysis == n_analysis))$info
```

At this point, `y` is defined such that `info` is under the alternative. Doesn't the column extracted from `y` need to toggle between `info` and `info0` depending on the user input value of `info_scale`?

**Comment by LittleBeannie** [comment]
Hi @mjg211, thank you for raising this valuable question! The `info_scale = ...` parameter determines whether the sample size is under null, alternative, or both scenarios. This concept is similar to the "Variance of log Hazard Ratio" in EAST, where you have the options of "Null" and "Alternative".

If you are interested in calculating the information, I suggest using the `pw_info()` function.

**Comment by mjg211** [comment]
Hi @LittleBeannie. Thanks for your response. I can see what `info_scale` is meant to do - I'm still not convinced it (or at least the output) is what it should be though. Maybe a better way of phrasing my question is what is the intended meaning of `info` and `info0` in the outputted `analysis` tibble? Surely the `info0` column should *always* be one quarter of the number of events? In the above it's clearly not as 295/4 is not 72.5.
