### ISSUE TITLE
Warnings from `fixed_design_rd()` caused by mismatched column names

### ISSUE THREAD

**Issue by jdblischak** [Merck/gsDesign2#296]
I noticed the following two warnings 

```R
devtools::test(filter = "fixed_design")
ℹ Testing gsDesign2
✔ | F W  S  OK | Context
✔ |   2      7 | independent-fixed_design [4.1s]

Warning (test-independent-fixed_design.R:130:3): RD
Unknown or uninitialised column: `theta`.
Backtrace:
    ▆
 1. └─gsDesign2::fixed_design_rd(...) at test-independent-fixed_design.R:130:3
 2.   └─gsDesign2::gs_design_rd(...) at gsDesign2/R/fixed_design_rd.R:96:5
 3.     ├─x$theta at gsDesign2/R/gs_design_rd.R:207:5
 4.     └─tibble:::`$.tbl_df`(x, theta) at gsDesign2/R/gs_design_rd.R:207:5

Warning (test-independent-fixed_design.R:130:3): RD
Unknown or uninitialised column: `info`.
Backtrace:
    ▆
 1. └─gsDesign2::fixed_design_rd(...) at test-independent-fixed_design.R:130:3
 2.   └─gsDesign2::gs_design_rd(...) at gsDesign2/R/fixed_design_rd.R:96:5
 3.     ├─x$info at gsDesign2/R/gs_design_rd.R:208:5
 4.     └─tibble:::`$.tbl_df`(x, info) at gsDesign2/R/gs_design_rd.R:208:5

══ Results 
Duration: 4.6 s

[ FAIL 0 | WARN 2 | SKIP 0 | PASS 7 ]
```

The two warnings are generated from a single call to `gs_design_rd()` that defines the argument `power`:

https://github.com/Merck/gsDesign2/blob/50067c424ab7dca4579ae895edc5de2bdcd9546e/tests/testthat/test-independent-fixed_design.R#L130-L133

Interestingly, the subsequent call to `gs_design_rd()` that defines `n` instead of `power` does not generate the warnings:

https://github.com/Merck/gsDesign2/blob/50067c424ab7dca4579ae895edc5de2bdcd9546e/tests/testthat/test-independent-fixed_design.R#L135-L138

When `power` is defined, `fixed_design_rd()` calls `gs_design_rd()`:

https://github.com/Merck/gsDesign2/blob/50067c424ab7dca4579ae895edc5de2bdcd9546e/R/fixed_design_rd.R#L85-L104

`gs_design_rd()` then calls `gs_info_rd()`, and expects the returned table to contain the columns `theta` and `info`:

https://github.com/Merck/gsDesign2/blob/50067c424ab7dca4579ae895edc5de2bdcd9546e/R/gs_design_rd.R#L206-L212

However, the result returned by `gs_info_rd()` does not contains these columns:

https://github.com/Merck/gsDesign2/blob/50067c424ab7dca4579ae895edc5de2bdcd9546e/R/gs_info_rd.R#L288

Surprisingly the tests continue to pass even though `theta1` and `info1` are assigned `NULL`. I thought that maybe the autocomplete feature of `$` still returned the correct values, but it can't distinguish between eg `theta1` and `theta0`

```R
x <- data.frame(theta1 = 1, theta0 = 0, info1 = 1, info0 = 0, long_name = 3)
x$theta
## NULL
x$info
## NULL
x$long
## [1] 3
```

**Comment by jdblischak** [comment]
I used `git bisect` to identify the first commit that generated the warnings. It was commit https://github.com/Merck/gsDesign2/commit/3c716711ec7a3a628e03d7aaadcf208fbba5174b from @LittleBeannie, in which the default value of `h1_spending` was changed from `FALSE` to `TRUE`.

Thus I think my proposed solution in #293 to set `h1_spending = FALSE` when calling `gs_design_rd()` would restore the previous behavior.

**Comment by nanxstats** [comment]
Keaven suggested that Yujie should weigh in, and using both h0 and h1 might be the best.

So let's revisit this after the holidays.

**Comment by LittleBeannie** [comment]
> I used `git bisect` to identify the first commit that generated the warnings. It was commit [3c71671](https://github.com/Merck/gsDesign2/commit/3c716711ec7a3a628e03d7aaadcf208fbba5174b) from @LittleBeannie, in which the default value of `h1_spending` was changed from `FALSE` to `TRUE`.
> 
> Thus I think my proposed solution in #293 to set `h1_spending = FALSE` when calling `gs_design_rd()` would restore the previous behavior.

Hi John, thanks for tracing back! Since gsDesign2 uses `h1_spending = TRUE` consistently for consistency with most of the clinical trial practice, I would suggest not to change it back to `FALSE`.

**Comment by LittleBeannie** [comment]
This issue is fixed in the PR of https://github.com/Merck/gsDesign2/pull/303. Please take a look and review, thanks!
