### ISSUE TITLE
Standardize code comment format

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#308]
## Problem

In some of the code in `R/` (and maybe `vignettes/`), a form of "ASCII art" was used to box the comments, looking like this:

```r
# ----------------------------#
#    check input values       #
# ----------------------------#
```

This format looks nice but might not be ideal for a few reasons:

- **Readability**: These comments are harder to read and write consistently. It will surely require extra effort to maintain the alignment of the boxes as the content of the comments change.
- **Searchability**: With a mixture of differently formatted boxes, code comments are harder to search and parse programmatically.
- **Portability**: The comments may not render properly in environments such as emails that do not support monospace fonts, where the box structure may not appear as intended.
- **Version control compatibility**: The more sophisticated formatting can complicate version control, making it harder to track changes and resolve conflicts in the long run.

---

## Proposed solution

Reformat the code comments with the standard format [tidyverse style guide](https://style.tidyverse.org/functions.html#comments-1). As I quote:

> Each line of a comment should begin with the comment symbol and a single space: `# `.
>
> Comments should be in sentence case, and only end with a full stop if they contain at least two sentences.

Also, if a section structure is needed, use the [standard convention](https://support.posit.co/hc/en-us/articles/200484568-Code-Folding-and-Sections-in-the-RStudio-IDE) that can be parsed in RStudio, preferably with trailing dashes (`-`):

> ... any comment line which includes at least four trailing dashes (`-`), equal signs (`=`), or pound signs (`#`) automatically creates a code section.

So, the above comment could become simply

```r
# Check input values ----
```

**Comment by nanxstats** [comment]
I will let @jdblischak do the honor 😉

**Comment by jdblischak** [comment]
What about multi-line comments? eg

https://github.com/Merck/gsDesign2/blob/e7cef1fb87dda31a049316687a1c32535a4c96c2/R/summary.R#L435-L441

My suggestion is:

```R
  # merge 2 tables: ----
  # (1) alternate hypothesis table
  # (2) null hypothesis table
  #
  # table A: a table under alternative hypothesis
  xy <- x_bound %>%
```

**Comment by nanxstats** [comment]
My simple proposal is to format them the way you write the Markdown-based roxygen comments. For lists, see [here](https://roxygen2.r-lib.org/articles/markdown.html#lists).

In this particular list case and long comments spanning multiple lines, I feel there is less of a need to even use `----` because it's a holistic thing and might not even be meaningful to only use the first line as the section header.

```r
  # Merge 2 tables:
  # 1. Alternate hypothesis table.
  # 2. Null hypothesis table.
  #
  # Table A: a table under alternative hypothesis.
  xy <- x_bound %>%
```
