### ISSUE TITLE
New Rcpp-related WARNING from R devel

### ISSUE THREAD

**Issue by jdblischak** [Merck/gsDesign2#310]
In PR #309, I got the following WARNING from R devel:

```
* checking whether package ‘gsDesign2’ can be installed ... [20s/26s] WARNING
Found the following significant warnings:
  /home/runner/work/_temp/Library/Rcpp/include/Rcpp/iostream/Rstreambuf.h:53:20: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 2 has type ‘std::streamsize’ {aka ‘long int’} [-Wformat=]
  /home/runner/work/_temp/Library/Rcpp/include/Rcpp/iostream/Rstreambuf.h:57:21: warning: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 2 has type ‘std::streamsize’ {aka ‘long int’} [-Wformat=]
  /home/runner/work/_temp/Library/Rcpp/include/Rcpp/print.h:30:19: warning: format not a string literal and no format arguments [-Wformat-security]
See ‘/home/runner/work/gsDesign2/gsDesign2/check/gsDesign2.Rcheck/00install.out’ for details.
```

This appears to be the same WARNING that was previously documented back in November in https://github.com/RcppCore/Rcpp/issues/1287 and was quickly fixed in a dev version. The latest 1.0.12 on CRAN is supposed to contain the fix

However, when I install the latest version of Rcpp and regenerate the files, `RcppExports.cpp` is not updated

```R
packageVersion("Rcpp")
## [1] ‘1.0.12’
Rcpp::compileAttributes()
```

**Comment by nanxstats** [comment]
Looks like it's fine in R-devel r85794 (2024-01-08) but appears in r85796 (2024-01-09). This change in `R CMD check` that stops filtering out such warnings is the reason: https://github.com/wch/r-source/commit/324558df2d0b1b9930837c59df0c5090c828ef70.

From the code comment above, it looks like the issue has been resolved in Rcpp. Checking CRAN shows that Rcpp has been updated to 1.0.12 on 2024-01-09, while the GitHub Action workflow is still using the cached 1.0.11 version from last July.

So the solution would be to simply clean up the cache in the GHA workflow so it can use both the latest R-devel and Rcpp release.

**Comment by nanxstats** [comment]
I deleted all caches via https://github.com/Merck/gsDesign2/actions/caches and reran all the workflows in the main branch.

However, it's still failing because the Rcpp on Posit Public Package Manager is still 1.0.11.

I will revisit this tomorrow or later.

**Comment by nanxstats** [comment]
Rcpp is still not updated on Posit Public Package Manager (P3M). I will check again next Monday as P3M does not sync package from CRAN at all on weekends.

**Comment by nanxstats** [comment]
OK P3M finally synced Rcpp 1.0.12. I cleared all caches again and reran the workflow on the main branch. Now it passes.
