### ISSUE TITLE
Improve input constructor implementations

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#316]
We received some feedback from Keaven on not being able to reuse the enroll/failure rate objects in the design object under the new `define_*()` input constructors and checking.

We should

1. Check why the classes of the rate objects returned by `gs_design_ahr()` is not preserved. (**need a minimal reproducible example** from Keaven).

2. Improve the warning message to soften the tune: it's possible to construct the object manually under certain conditions, for example, with certain classes assigned.

**Comment by nanxstats** [comment]
Proposal from @jdblischak: validate if the input is a valid input, instead of a certain class.

**Comment by jdblischak** [comment]
Here is a quick reproducible example that produces the warning messages:

```R
library("gsDesign2")

enroll_rate <- define_enroll_rate(
  duration = c(2, 2, 10),
  rate = c(3, 6, 9)
)
class(enroll_rate)
## [1] "enroll_rate" "tbl_df"      "tbl"         "data.frame" 
gs_design_ahr(enroll_rate = enroll_rate)

# remove the class
class(enroll_rate) <- class(enroll_rate)[-1]
class(enroll_rate)
## [1] "tbl_df"     "tbl"        "data.frame"
gs_design_ahr(enroll_rate = enroll_rate)
## Warning messages:
##   1: In check_enroll_rate(enroll_rate) :
##   Please use `define_enroll_rate()` to specify the `enroll_rate` argument.
## We will enforce this requirement from the next version.
## 2: In check_enroll_rate(enroll_rate) :
##   Please use `define_enroll_rate()` to specify the `enroll_rate` argument.
## We will enforce this requirement from the next version.
## 3: In check_enroll_rate(enroll_rate) :
##   Please use `define_enroll_rate()` to specify the `enroll_rate` argument.
## We will enforce this requirement from the next version.
```

So I plan to update the function `check_enroll_rate()` to verify the input instead of enforcing the class. If the input is invalid, I will have the error message recommend the user try the helper function `define_enroll_rate()`

https://github.com/Merck/gsDesign2/blob/187edf339dcb6c953aa9dd3998560310803c1cf1/R/check_arg.R#L109-L116
