### ISSUE TITLE
gs_design_ahr: specifying info_frac without knowing the analysis_time

### ISSUE THREAD

**Issue by eric-zhang16** [Merck/gsDesign2#323]
Is it possible to design a trial using gs_design_ahr with a fixed sample size and information fractions without analysis_time? thanks

**Comment by LittleBeannie** [comment]
Hello @eric-zhang16 , could you please use the `gs_power_ahr()` function? When entering the `enroll_rate = ...` parameter, ensure that the sum of the product of duration and time is equal to the sample size you have. Additionally, please attempt to provide the information fraction using the `event = ...` argument.
