### ISSUE TITLE
Add tests of RD related functions

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#34]
The functions to be tested include: 

- `gs_design_rd.R`
- `gs_power_rd.R`
- `gs_info_rd.R`

The above 3 functions are new in `gsDesign2` and there are no old testing codes to borrow from.

**Comment by elong0527** [comment]
Please help. What does `rd` stands for?

**Comment by LittleBeannie** [comment]
> Please help. What does `rd` stands for?

RD = risk difference
