### ISSUE TITLE
Revert back `create_arm()` workaround after bug fix in upstream

### ISSUE THREAD

**Issue by nanxstats** [Merck/gsDesign2#346]
## Context

There is an if-condition that needs to be improved to be less stringent in the upstream dependency npsurvSS. Detailed analysis documented in #344.

We merged the short term solution (copy the original implementation, modify that condition, and make it an internal function) in #345.

## Next steps

- [x] Send a PR to the upstream repo to fix the issue and ask for a CRAN release.

Once this is fixed upstream and made it to CRAN, we should

- [x] Revert the changes in PR 345 so we rely on the upstream implementation.
- [x] Add the minimum version required (`npsurvSS (>= x.y.z)`) to `DESCRIPTION`.

**Comment by LittleBeannie** [comment]
PR to npsurvSS: https://github.com/godwinyyung/npsurvSS/pull/4

Timeline: CRAN release by 3/11/2024

**Comment by nanxstats** [comment]
Update: npsurvSS 1.1.0 is on CRAN 2024-05-08.

**Comment by nanxstats** [comment]
Fixed by #391
