### ISSUE TITLE
Bug of `as_gt()` when using full alpha < 0.025

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#349]

**Comment by LittleBeannie** [comment]
Considering that this is not a bug and the inclusion of the `full_alpha = ...` argument resolves the issue, I recommend closing this issue as 'not planned'

**Comment by nanxstats** [comment]
hey @LittleBeannie could you put the original question in the description so it's clear what was the asked for future references?

**Comment by LittleBeannie** [comment]
> hey @LittleBeannie could you put the original question in the description so it's clear what was the asked for future references?

Thanks for the suggestion. The details will be explained in the new issue.
