### ISSUE TITLE
Footnotes from `as_gt` when the total alpha is < 0.025

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#384]
The following one-sided design spends a total alpha of 0.0125.
```
x <- gs_design_ahr(
  alpha = 0.0125,
  analysis_time = c(12, 24, 36),
  upper = gs_spending_bound,
  upar = list(sf = gsDesign::sfLDOF, total_spend = 0.0125, param = NULL),
  lower = gs_b,
  lpar = rep(-Inf, 3)
)
```
It has a list output containing `input`, `enroll_rate`, `fail_rate`, `bound`, and `analysis`.
![image](https://github.com/Merck/gsDesign2/assets/43153957/b2d7707c-06e4-4d4b-8ad1-c4612960bfcc)

Rather than using the list output directly, users commonly employ the `summary()` function to generate a summarized table of the design details described above.
```
x |> summary()
```
![image](https://github.com/Merck/gsDesign2/assets/43153957/fd29487a-18c6-4f1c-a5de-582eaff5541d)

As evident from the summary output provided above, we observe that the total spent alpha information is NOT included. However, this information is crucial for incorporating the above summary table into a gt table for the footnotes. To address this, we can
```
x |> summary() |> as_gt()
x |>summary() |> as_gt(alpha = 0.0125)
```
![image](https://github.com/Merck/gsDesign2/assets/43153957/fc2d66a4-8e09-4659-a6a0-cff1a047cbe4)
![image](https://github.com/Merck/gsDesign2/assets/43153957/b7a5f53f-9fe1-4627-bb46-7c9fbcf9a11b)

**Question:** is there anyway to get the full alpha information from the summary table to the gt table?

**Comment by LittleBeannie** [comment]
**Decision:** add one more column of planned alpha spending in the summary table, but "hide" this column in the summary table via the "attribute" property. And this hidden column can be passed to the gt table.

**Comment by jdblischak** [comment]
> add one more column of planned alpha spending in the summary table, but "hide" this column in the summary table via the "attribute" property

Two follow-up points:

* If the alpha spending column is informative to the end user, then I recommend displaying it to them in the output from `summary()`. If I understand correctly, in that case we wouldn't need to use attributes
* If we aren't going to show the new column via `summary()` or `as_gt()`, then I don't think we should bother calculating it. It will be simpler to pass a single value of total `alpha` via an attributes instead of a vector

**Comment by LittleBeannie** [comment]
> > add one more column of planned alpha spending in the summary table, but "hide" this column in the summary table via the "attribute" property
> 
> Two follow-up points:
> 
> * If the alpha spending column is informative to the end user, then I recommend displaying it to them in the output from `summary()`. If I understand correctly, in that case we wouldn't need to use attributes
> * If we aren't going to show the new column via `summary()` or `as_gt()`, then I don't think we should bother calculating it. It will be simpler to pass a single value of total `alpha` via an attributes instead of a vector

By default, users are not interested in alpha spending column. Considering this, shall we pass a single value of total alpha via an attributes instead of a vector?

**Comment by jdblischak** [comment]
> shall we pass a single value of total alpha via an attributes instead of a vector?

Makes sense to me!
