### ISSUE TITLE
Custom number of digits in the summary-gt table

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#388]
Suppose we have a design 
```
x <- gs_design_ahr(analysis_time = c(12, 24)) 
```

When we summarize it into a gt table, we run
```
x |> summary() |> as_gt()
```
![image](https://github.com/Merck/gsDesign2/assets/43153957/555a4985-ea4f-4b71-a581-13f6d5375d7f)

The default summary-gt table displays **two** decimals for the AHR and information fraction. However, users may have a preference for displaying more decimals. To accomplish this, users can use the following method:

```
x |> 
    summary(analysis_vars = c("time", "n", "event", "ahr", "info_frac"),
                    analysis_decimals = c(2, 0, 0, 4, 4)) |> 
    as_gt()
```
![image](https://github.com/Merck/gsDesign2/assets/43153957/4a1fe493-a3b5-4d45-b936-384426fc9f9e)

**Questions:**

1. Any better syntax available?
2. If the above syntax is implemented correctly, the following lines of code should work:

```
x |> 
    summary(analysis_vars = c("ahr", "info_frac"),
                    analysis_decimals = c(4, 4)) |> 
    as_gt()
```
![image](https://github.com/Merck/gsDesign2/assets/43153957/0f101f1c-6cc1-45c6-81d0-b7d3dd122ba6)

**Comment by jdblischak** [comment]
I noticed that there are analogous function arguments `col_vars` and `col_decimals`. If I am going to update `analysis_decimals` to be more flexible (current plan is for it to accept a named vector), should I also update `col_decimals` to behave the same?

https://github.com/Merck/gsDesign2/blob/58f9ffbfa0a3ffd2196845e2d3ccf0355e90a354/R/summary.R#L148-L151

**Comment by jdblischak** [comment]
Also, I am realizing this Issue is related to the existing Issue #282 to tidy up the `summary()` and `as_gt()` functions. Both `analysis_decimals` and `col_decimals` are defined in various `if (method == "")` blocks. We might be able to make more specific summary functions for each method, eg `summary.ahr()`

**Comment by LittleBeannie** [comment]
> I noticed that there are analogous function arguments `col_vars` and `col_decimals`. If I am going to update `analysis_decimals` to be more flexible (current plan is for it to accept a named vector), should I also update `col_decimals` to behave the same?
> 
> https://github.com/Merck/gsDesign2/blob/58f9ffbfa0a3ffd2196845e2d3ccf0355e90a354/R/summary.R#L148-L151

Yes, please!
