### ISSUE TITLE
The function documentation for `gs_b()` needs updated

### ISSUE THREAD

**Issue by jdblischak** [Merck/gsDesign2#414]
I noticed that the function documentation for `gs_b()` is outdated:

https://github.com/Merck/gsDesign2/blob/cb91f5d6e16317490c56b6b4a1c80602a4c0481f/R/gs_b.R#L21-L28

As rendered in the [pgkdown site](https://merck.github.io/gsDesign2/reference/gs_b.html):

![image](https://github.com/Merck/gsDesign2/assets/1608317/e384724d-33d5-4ab4-b92e-ff812cdbf675)

Problems I noticed:

* `gs_prob()`, `gs_power_nph()`, and `gs_power_nph()` have all been renamed
* While the first argument accepts Z-values, it is not named `Z` but `par`
* `par[k]j` should be `par[k]`
* It begins to suggest other functions to use for boundaries that change based on the information, but then never names any

**Comment by nanxstats** [comment]
The solution for the first item is simple: always [link to functions](https://roxygen2.r-lib.org/articles/markdown.html#links) with the `[func()]` syntax in roxygen2 docs. roxygen2 would generate an error if the function names are changed while the docs are out of sync.

The other items can probably use a simple fix.

**Comment by jdblischak** [comment]
> always [link to functions](https://roxygen2.r-lib.org/articles/markdown.html#links) with the `[func()]` syntax in roxygen2 docs.

Good suggestion!

> roxygen2 would generate an error if the function names are changed while the docs are out of sync.

Almost. When I ran `devtools::document()`, it was happy to insert a broken link. But it was caught by `R CMD check`, which throws a WARNING for bad cross-references:

```R
W  checking Rd cross-references (915ms)
   Missing link or links in documentation object 'gs_b.Rd':
     'gs_prob'

   See section 'Cross-references' in the 'Writing R Extensions' manual.
```
