### ISSUE TITLE
`gs_power_wlr()` examples are not running for `as_gt()`

### ISSUE THREAD

**Issue by yuliasidi** [Merck/gsDesign2#423]
Please consider updating examples in the `as_gt()` documentation. Currently some examples are producing errors, please see below.
```
> # Example 2 ----
> # Usage of title = ..., subtitle = ...
> # to edit the title/subtitle
> gs_power_wlr() %>%
+   summary() %>%
+   as_gt(
+     title = "Bound Summary",
+     subtitle = "from gs_power_wlr"
+   )
Error in gs_power_wlr() : 
  gs_power_wlr: please input the total_spend to the futility spending function.
```

**Comment by LittleBeannie** [comment]
Hi @yuliasidi , this is a problem raising in your implementation of `gs_power_wlr`, not `as_gt`. We test futility with spending function as default. However, you have not specified the total spend of the futility. 

The default `lpar` is `list(sf = gsDesign::sfLDOF, total_spend = NULL)`. You will find the `total_spend` is `NULL`. Please assign a number there and the problem will be solved.
