### ISSUE TITLE
More convenient `col_decimals` for `summary.gs_design()`

### ISSUE THREAD

**Issue by yuliasidi** [Merck/gsDesign2#428]
Please consider adding a simplified way for modifying the column digits in the table. 
Currently a user needs to run the following code to modify the number of digits for Z value to 4:
```
tmp_gsDesign2 |>
  summary(
    col_vars = c("analysis", "bound", "z", "~hr at bound", "nominal p", "Alternate hypothesis", "Null hypothesis"),
    col_decimals = c(NA, NA, 4, 4, 4, 4, 4)
  ) 
```
It would be helpful to have instead the following option and call out only what needs to be modified:
```
tmp_gsDesign2 |>
  summary(
    col_vars = "z",
    col_decimals = 4
  ) 
```
For your consideration.

**Comment by jdblischak** [comment]
> Please consider adding a simplified way for modifying the column digits in the table.

We recently updated the syntax for modifying the number of digits via `analysis_decimals` (#388, #403), and we plan to update `col_decimals` similarly.

> It would be helpful to have instead the following option and call out only what needs to be modified:

Your proposed syntax isn't possible because `col_vars` is also used to subset the displayed columns. Thus `col_vars = "z"` would result in only the `z` column being displayed. For the analogous `analysis_decimals`, we updated it to accept a named vector. So in the future the hope is for your example to be possible with:

```R
tmp_gsDesign2 |>
  summary(col_decimals = c(z = 4)) 
```

Also note that as of last week (https://github.com/Merck/gsDesign2/pull/422), you should now be able to omit both `"analysis"` and `"bound"`, so it at least a bit shorter to type:

```R
tmp_gsDesign2 |>
  summary(
    col_vars = c("z", "~hr at bound", "nominal p", "Alternate hypothesis", "Null hypothesis"),
    col_decimals = c(4, 4, 4, 4, 4)
  ) 
```

Lastly, I am going to update the title of your Issue. `col_vars` and `col_decimals` are arguments to `summary.gs_design()`, not `summary.fixed_design()`.

**Comment by yuliasidi** [comment]
Thank you, @jdblischak! 
I tried the change from the (#422), but I am getting an error:
```
> gs_power_ahr(lpar = list(sf = gsDesign::sfLDOF, total_spend = 0.1)) |> summary(col_decimals = c(z = 4))
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
In addition: Warning message:
Unknown or uninitialised column: `col_vars`. 
> 
> packageVersion("gsDesign2")
[1] ‘1.1.2.13’
```

**Comment by jdblischak** [comment]
> I tried the change from the (https://github.com/Merck/gsDesign2/pull/422), but I am getting an error:

@yuliasidi Using `col_decimals = c(z = 4)` is not possible yet. This Issue is now the placeholder for that new behavior.

#422 allows you to omit `"analsysis"` and `"bound"` and their corresponding `NA`s:

```R
library("gsDesign2")
gs_power_ahr(lpar = list(sf = gsDesign::sfLDOF, total_spend = 0.1)) |>
  summary(
    col_vars = c("z", "~hr at bound", "nominal p", "Alternate hypothesis", "Null hypothesis"),
    col_decimals = c(4, 4, 4, 4, 4)
  )
## Adding missing grouping variables: `Analysis`
## # A tibble: 6 × 7
## # Groups:   Analysis [3]
##   Analysis      Bound      Z `~HR at bound` `Nominal p` `Alternate hypothesis` `Null hypothesis`
##   <chr>         <chr>  <dbl>          <dbl>       <dbl>                  <dbl>             <dbl>
## 1 Analysis: 1 … Futi… -1.17           1.54       0.879                  0.0349            0.121 
## 2 Analysis: 1 … Effi…  2.67           0.374      0.0038                 0.0231            0.0038
## 3 Analysis: 2 … Futi… -0.663          1.24       0.746                  0.0668            0.266 
## 4 Analysis: 2 … Effi…  2.29           0.481      0.011                  0.0897            0.0122
## 5 Analysis: 3 … Futi… -0.227          1.07       0.590                  0.101             0.430 
## 6 Analysis: 3 … Effi…  2.03           0.560      0.0211                 0.207             0.025
```

**Comment by LittleBeannie** [comment]
Hi @yuliasidi , thanks for exploring the decimal display of the `summary` function. It looks like your question is solved in the above discussion. I understand the current version of `summary` does exist some inconvenience of displaying digits, and @jdblischak is actively working on this (see the open issue https://github.com/Merck/gsDesign2/issues/430). We will keep you posted once we finished.

Hi @jdblischak, I created an issue (https://github.com/Merck/gsDesign2/issues/430) to remind us of the `col_decimals` in `summary()`, and assigned this issue to you. Please reach out me if anywhere I could assist.
