### ISSUE TITLE
The test at `test-independent-fixed_design.R:141` is not stable

### ISSUE THREAD

**Issue by yihui** [Merck/gsDesign2#451]
https://github.com/Merck/gsDesign2/blob/32277b84a28748b9adfcd56b11f27bf7529b0ec1/tests/testthat/test-independent-fixed_design.R#L141

It throws an error sporadically, e.g.,

- macOS: https://github.com/Merck/gsDesign2/actions/runs/10364093136/job/28688800583   
- Ubuntu: https://github.com/Merck/gsDesign2/actions/runs/10371574081/job/28712193416

The tolerance was recently raised with e9317fd99fe8b616f5d9bf49c04ed2191d748406 but may still not be enough.

**Comment by nanxstats** [comment]
Apparently, I'm not the stats expert here but @elong0527 how about we set `tolerance = 1e-4` explicitly, meaning power = 90.009 is ok but power = 90.01 is not ok.

**Comment by elong0527** [comment]
I like a explicit criteria as well.

**Comment by LittleBeannie** [comment]
Thanks for pointing it out, @yihui ! I guess there are 2 issues leading to the instability of the testing:

1. A numerical issue. From [line 118](https://github.com/Merck/gsDesign2/blob/32277b84a28748b9adfcd56b11f27bf7529b0ec1/tests/testthat/test-independent-fixed_design.R#L118)-127, I calculate the sample size to get 90% power, which is around 415.7804. Then, from [line 130](https://github.com/Merck/gsDesign2/blob/32277b84a28748b9adfcd56b11f27bf7529b0ec1/tests/testthat/test-independent-fixed_design.R#L130) - 139, I input the sample size of 415.7804 via the implementation of [line 132](https://github.com/Merck/gsDesign2/blob/32277b84a28748b9adfcd56b11f27bf7529b0ec1/tests/testthat/test-independent-fixed_design.R#L132), to check if the sample size gives me 90% power of not. 
If you look into line 132, you will notice I did something like `x/y*y`. As we discussed before, it is theoretically true, but not hold for laptop numerical calculation. So `y`'s sample size (line 130) is slightly different from 415.7804, which leading a power slightly different of 90%. In my laptop, I got `y`'s power is 0.899991, which fails when I run `expect_equal(0.899991, 0.9)`.

4. A random number issue. For the MaxCombo test, there are some random number issues, as Nan bring up in https://github.com/Merck/gsDesign2/issues/340.

**Comment by yihui** [comment]
Got it. Then it seems we need to either raise the tolerance (as I did in PR #455) or set a seed. I noticed that we were using a higher tolerance (0.01) for other tests: https://github.com/Merck/gsDesign2/blob/main/tests/testthat/test-independent-fixed_design.R so I wonder why this test was given a much smaller tolerance.
