### ISSUE TITLE
Development Version

### ISSUE THREAD

**Issue by elong0527** [Merck/gsDesign2#54]
In #53, should we use `0.1.0.9000` or `0.2.0.9000`? If it is `0.2.0.9000`, we probably should write NEWS for `0.2.0`

cc: @nanxstats , @LittleBeannie

**Comment by elong0527** [comment]
Then, could we provide NEWS for 0.2.0?

**Comment by nanxstats** [comment]
0.2.0.9000 is good, and I see you added news for 0.2.0.

**Comment by LittleBeannie** [comment]
> 0.2.0.9000 is good, and I see you added news for 0.2.0.

Yes! But we don't have a release for 0.1.0 yet... and it looks like the commit for 0.1.0 (389aed0) is too old to be a "recent commit" to release. Do you have any quick solutions?

**Comment by fb-elong** [comment]
Per #53, we can close this ticket.

**Comment by nanxstats** [comment]
Great!
