### ISSUE TITLE
Add parameter to wMB

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/gsDesign2#78]
To align with `simtrial` and support the recommendation of Magirr, Dominic. "Non‐proportional hazards in immuno‐oncology: Is an old perspective needed?." Pharmaceutical Statistics 20.3 (2021): 512-527. Sets a maximum weight for a modestly weighted logrank test. Shall we also update the weighting functions?

**Comment by elong0527** [comment]
Could you provide the formula to be implemented? Or indicate the formula number in the paper.

**Comment by LittleBeannie** [comment]
> Could you provide the formula to be implemented? Or indicate the formula number in the paper.

Hi Yilong, I haven't got time to take a close look at the paper yet. Will get back to you later.

**Comment by nanxstats** [comment]
Keaven's patch for simtrial: https://github.com/Merck/simtrial/pull/22

**Comment by nanxstats** [comment]
Fixed by https://github.com/Merck/gsDesign2/pull/106
